### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by kurtts11** [pielco11/telescan#1]
After selecting item 1, an error message appears
```
Traceback (most recent call last):
  File "telescan.py", line 108, in <module>
    dialogs = app.get_dialogs()['dialogs']
TypeError: list indices must be integers or slices, not str
```

After selecting item 3, an error message appears
```
Traceback (most recent call last):
  File "telescan.py", line 133, in <module>
    dialogs = app.get_dialogs()['dialogs']
TypeError: list indices must be integers or slices, not str
```

**Comment by pielco11** [comment]
Hi @kurtts11 

I guess that the lib changed the structure of the data, let me check and I'll update the new code

**Comment by pielco11** [comment]
Quite late

Should work by now

**Comment by Peedro22** [comment]
Good,

Selecting option 3 shows the following, the same error that was mentioned above, what could it be?

`Traceback (most recent call last):
  File "telescan.py", line 133, in <module>
    dialogs = app.get_dialogs()['dialogs']
TypeError: list indices must be integers or slices, not str`
